#!/usr/bin/env bash
# netj's dotfiles installer
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2006-05-21

set -e

cd ~/.dotfiles || . update

# install symlinks
install() {
    local d=$1
    local n=$d
    # sanitize name
    n=${n#.}
    n=${n//[\/.-]/_}
    # compute relative path
    local rel=
    case $d in
        */*) # need relative path to .dotfiles if path has depth
        local dd=`dirname $d` 
        mkdir -p ~/$dd
        rel=$(tr / '\n' <<<$dd |
            sed -n '/^$/d; s/.*/../p' |
            tr '\n' /)
        ;;
    esac
    run ${n}_before
    if [ x"`readlink ~/$d`" = x"$rel.dotfiles/$d" ]; then
        echo "$d installed"
        run ${n}_after
    else
        if read -p "install $d? " -n1; then
            echo
            case "$REPLY" in
                [Yy])
                # backup previous one
                ! [ -e ~/$d ] || mv -iv ~/$d ~/$d~
                # create a symlink
                ln -sfnv $rel.dotfiles/$d ~/$d
                run ${n}_after
                ;;
            esac
        fi
    fi
}
run() { [ "`type -t $1 2>/dev/null`" != function ] || (cd; "$@"); }
safeln() {
    local src=$1; shift
    local tgt=
    for tgt in "$@"; do
        if [ -e "$tgt" ]; then
            [ "`readlink "$tgt"`" != "$src" ] || continue
            mv -iv "$tgt" "$tgt~"
        fi
        [ -e "$tgt" ] || ln -sfnv "$src" "$tgt"
    done
}

# core
bash_after() {
    # .bash{rc,_profile} symlinks
    (cd
    safeln .bash/.profile .bash{rc,_profile}
    safeln .bash/.logout .bash_logout
    )
}
install .bash
install .inputrc

vim_after() { make -C .vim; }
install .vimrc
install .vim

install .tmux.conf
install .screenrc
install .toprc

emacs_d_elisp_Makefile_after() { make -C .emacs.d/elisp; }
install .emacs
install .emacs.d/elisp/Makefile


# GUI
fonts_after() { make -C .fonts; }
install .fonts.conf
install .fonts
