#!/usr/bin/env bash
# netj's dotfiles updater
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2006-05-21

Repo=sparcs
RepoURL_home=http://netj.org/dotfiles
RepoURL_sparcs=http://sparcs.org/~netj/dotfiles

set -e
cd
if type git >/dev/null; then
    # try with git
    [ -d .dotfiles ] || mkdir -p .dotfiles
    cd .dotfiles
    [ -d .git ] || git init
    for r in ${!RepoURL_*}; do 
        rn=${r#RepoURL_}
        git remote rm $rn || true
        git remote add $rn ${!r}/.git
    done
    git pull $Repo master
    git fetch $Repo
else
    # or just download everything with wget
    mkdir -p .dotfiles
    cd .dotfiles
    RepoURL=RepoURL_$Repo
    RepoURL=${!RepoURL}
    depth=$(sed 's$.\+://[^/]*/$$' <<<$RepoURL | tr / '\n' | wc -l)
    wget -qO- $RepoURL/INDEX |
    sed 's,^,'$RepoURL'/,' |
    wget -nv -N -r -np -nH --cut-dirs=$depth -i-
fi

# take care of attributes
xon() { [ -x $1 ] || ! [ -f $1 ] || chmod +x $1; }
xon install; xon update

