#!/bin/sh
set -e

trap "rm -f .git/tags.$$" EXIT

# trying to find universal ctags
case $(uname) in
  Darwin)
    eval "$(/usr/libexec/path_helper)"
    PATH=/opt/homebrew/bin:"$PATH"
    ;;
esac

# universal ctags
git ls-files | ctags --tag-relative -L - -f".git/tags.$$" #--languages=-json

# TODO fallback to macOS ctags when unavailable

mv -f .git/tags.$$ .git/tags
