#!/bin/sh
set -e

TOPLEVEL=$(git rev-parse --show-toplevel)

trap "rm -f \"$TOPLEVEL/tags.$$\"" EXIT

# trying to find universal ctags
case $(uname) in
  Darwin)
    eval "$(/usr/libexec/path_helper)"
    PATH=/opt/homebrew/bin:"$PATH"
    ;;
esac

# universal ctags
git ls-files | ctags --tag-relative -L - -f"$TOPLEVEL/tags.$$" #--languages=-json

# TODO fallback to macOS ctags when unavailable

mv -f "$TOPLEVEL/tags.$$" "$TOPLEVEL/tags"
