#!/usr/bin/env bash
# netj's bash module: common environment
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2002-07-15

bash_autoload=true

bash_import() {
    # variables
    hostnickname=${HOSTNAME%%.*}
    hostdomain=${HOSTNAME#*.}
    #  Korean
    bash_default_env LANG ko_KR.UTF-8
    bash_default_env LC_ALL $LANG
    bash_default_env LANGUAGE $LANG
    local uname=`uname`
    # platform specific settings
    case $uname in
        Darwin) # Mac OS X
            # some stuffs get installed on /usr/local
            bash_insert_path PATH /usr/local/sbin /usr/local/bin
            bash_insert_path MANPATH /usr/local/man /usr/local/share/man
            PATH=/usr/local/bin:$PATH  # XXX We need to force /usr/local/bin in front of /usr/bin since the default path_helper(8) keeps it after /usr/bin
            if type brew &>/dev/null; then
                # Prefer Homebrew (http://mxcl.github.com/homebrew/)
                local brewPrefix=`brew --prefix`
                bash_insert_path PATH "$brewPrefix"/sbin "$brewPrefix"/bin
                bash_insert_path MANPATH "$brewPrefix"/man "$brewPrefix"/share/man
            elif [ -x /opt/local/bin/port ]; then
                # Paths for MacPorts (http://www.macports.org/)
                bash_insert_path PATH /opt/local/sbin /opt/local/libexec/gnubin /opt/local/bin
                bash_insert_path MANPATH /opt/local/man /opt/local/share/man
            fi
        ;;
    esac
    # add ~/bin to PATH
    bash_insert_path PATH ~/bin
}

bash_login() {
    # environment variables
    bash_default_env EDITOR vim
    bash_default_env PAGER less
    bash_default_env LESS "-XFRiMW" # --no-init --quit-if-one-screen --RAW-CONTROL-CHARS --ignore-case --LONG-PROMPT --HILITE_UNREAD
    #  TeX
    bash_default_env TEXINPUTS ".:$HOME/.tex:"
    # some usability options
    shopt -s nocaseglob cdspell cmdhist
    local uname=`uname`
    # ls on several platforms
    local ls_o=
    if ls --version 2>&1 | grep 'Free Software Foundation' >/dev/null; then
        # GNU ls
        ls_o="-F --color=auto"
        [ -n "$LS_COLORS" ] || eval "`dircolors -b 2>/dev/null`"
        # platform specific configs
        case $uname in
            CYGWIN*) ls_o="$ls_o --show-control-chars" ;;
        esac
    else
        # platform specific ls
        case $uname in
            *BSD|Darwin) ls_o="-FG" ;;
        esac
    fi
    bash_default_alias ls "ls $ls_o"
    # ls idioms
    bash_default_alias ll "ls -l"
    bash_default_alias la "ls -A"
    bash_default_alias lal "la -l"
    bash_default_alias lt "ls -t"
    bash_default_alias llt "ll -t"
    bash_default_alias lalt "lal -t"
    # frequently used abbreviations
    bash_default_alias cp "cp -i"
    bash_default_alias mv "mv -i"
    bash_default_alias rm "rm -i"
    # keep history clean
    HISTIGNORE="&:l[salt]:lal:llt:lalt:[bf]g:cd"
}

# vim:et:ts=8:sw=4:sts=4
