#!/usr/bin/env bash
# netj's bash module: common environment
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2002-07-15

bash_autoload=true

bash_import() {
    # variables
    hostnickname=${HOSTNAME%%.*}
    hostdomain=${HOSTNAME#*.}
    #  Korean
    bash_default_env LANG ko_KR.UTF-8
    bash_default_env LC_ALL $LANG
    bash_default_env LANGUAGE $LANG
    # add ~/bin to PATH
    if [ -d ~/bin ] && ! expr "$PATH" : "$HOME/bin:" >/dev/null; then
        PATH=~/bin:"$PATH"
    fi
    local uname=`uname`
    # platform specific settings
    case $uname in
        Darwin) # Mac OS X
        # some packages install stuffs on /usr/local
        export PATH=/usr/local/bin:/usr/local/sbin:$PATH
        export MANPATH=/usr/local/man:$MANPATH

        # Setting paths for MacPorts
        export PATH=/opt/local/bin:/opt/local/libexec/gnubin:/opt/local/sbin:$PATH
        export MANPATH=/opt/local/man:$MANPATH
        ;;
    esac
}

bash_login() {
    # environment variables
    bash_default_env EDITOR vim
    bash_default_env PAGER less
    bash_default_env LESS "-XFRiMW" # --no-init --quit-if-one-screen --RAW-CONTROL-CHARS --ignore-case --LONG-PROMPT --HILITE_UNREAD
    #  TeX
    bash_default_env TEXINPUTS ".:$HOME/.tex:"
    # some usability options
    shopt -s nocaseglob cdspell cmdhist
    local uname=`uname`
    # ls on several platforms
    local ls_o=
    if ls --version 2>&1 | grep 'Free Software Foundation' >/dev/null; then
        # GNU ls
        ls_o="-F --color=auto"
        [ -n "$LS_COLORS" ] || eval "`dircolors -b 2>/dev/null`"
        # platform specific configs
        case $uname in
            CYGWIN*) ls_o="$ls_o --show-control-chars" ;;
        esac
    else
        # platform specific ls
        case $uname in
            *BSD|Darwin) ls_o="-FG" ;;
        esac
    fi
    bash_default_alias ls "ls $ls_o"
    # ls idioms
    bash_default_alias ll "ls -l"
    bash_default_alias la "ls -A"
    bash_default_alias lal "la -l"
    bash_default_alias lt "ls -t"
    bash_default_alias llt "ll -t"
    bash_default_alias lalt "lal -t"
    # frequently used abbreviations
    bash_default_alias cp "cp -i"
    bash_default_alias mv "mv -i"
    bash_default_alias rm "rm -i"
    # keep history clean
    HISTIGNORE="&:l[salt]:lal:llt:lalt:[bf]g:cd"
}

# vim:et:ts=8:sw=4:sts=4
