#!/usr/bin/env bash
# netj's bash module: gpg-agent launcher
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2007-08-23

bash_load() {
    if [ -z "$GPG_AGENT_INFO" ]; then
        # gpg-agent for Debian has a nice script, try it first
        for x in /etc/X11/Xsession.d/*gpg-agent; do
            if [ -r "$x" ]; then
                . "$x"
                return
            fi
        done
        if type gpg-agent 2>/dev/null &&
            grep -qs '^[[:space:]]*use-agent' \
                "$GNUPGHOME/gpg.conf" "$GNUPGHOME/options"; then
            local gpg_agent_info=~/.gnupg/gpg-agent-info-`hostname`
            # launch gpg-agent if no agent is there
            if ! gpg-agent 2>/dev/null; then
                gpg-agent --daemon --sh >"$gpg_agent_info"
            fi
            # import gpg-agent-info
            if [ -r "$gpg_agent_info" ]; then
                . "$gpg_agent_info"
            fi
        fi
    fi
}

# vim:et:ts=8:sw=4:sts=4
