#!/usr/bin/env bash
# netj's bash module: welcome
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2005-06-08

bash_autoload=true

bash_load() {
    # start the welcome script
    [ -t 0 -a -x ~/.welcome ] && ~/.welcome
}

# vim:et:ts=8:sw=4:sts=4
