#!/usr/bin/env bash
# bash_completion loader
# 
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2002-07-15
# See: http://www.caliban.org/bash/
################################################################################

bash_plugin_interactive() {
    ## Check for bash (and that we haven't already been sourced).
    #[ -z "$BASH_VERSION" -o -n "$BASH_COMPLETION" ] && return
    [ -z "$BASH_COMPLETION" ] || return

    # Check for recent enough version of bash.
    local bash bmajor bminor
    bash=${BASH_VERSION%.*}; bmajor=${bash%.*}; bminor=${bash#*.}
    if [ $bmajor -eq 2 -a $bminor '>' 04 ] || [ $bmajor -gt 2 ]; then
        local bash_completions bash_completions_more
        bash_completions=()
        bash_completions_more=()
        # load completion for Homebrew
        if type brew &>/dev/null; then
            local brew_prefix=${brew_prefix:-$(brew --prefix)}
            bash_completions+=("$brew_prefix"/etc/bash_completion)
            [ $bmajor -lt 4 ] || bash_completions+=("$brew_prefix"/share/bash-completion/bash_completion)
            bash_completions_more+=(
                "$brew_prefix"/Library/Contributions/brew_bash_completion.sh
            )
        fi
        # look for other standard places
        bash_completions+=({/opt/local/etc,/usr/local/etc,/etc}/bash_completion)
        local f=
        for f in "${bash_completions[@]}"; do
            if [ -r "$f" ]; then
                BASH_COMPLETION=$f
                . "$f"
                break
            fi
        done
        # once BASH_COMPLETION is available, source more
        [ -n "$BASH_COMPLETION" ] || return
        for f in "${bash_completions_more[@]}"; do
            [ ! -r "$f" ] || . "$f"
        done
    fi
}

# vim:et:ts=8:sw=4:sts=4
