#!/usr/bin/env bash
# Bash scripting idioms
# 
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2022-06-04
################################################################################

bash_plugin_load() {

    # command prefix for displaying commands before running
    + () { set -x; "$@"; { set +x; } 2>/dev/null; }

    error() { echo >&2 "$@"; false; }


    @q() {
      local quoted=$({ set +x; } 2>/dev/null; exec 2>&1; PS4=; set -x; : "$@")
      echo "${quoted:2}"  # lstrip the ': ' prefix to get the compact bash-quoted form
    }

}
