#!/usr/bin/env bash
# Kubernetes aliases and etc.
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2019-08-28
# Requires: bpm.utils
################################################################################

bash_plugin_interactive() {
    if type kubectl &>/dev/null; then
        source <(kubectl completion bash)
        bash_default_alias kG    "kubectl get"
        bash_default_alias kd    "kubectl describe"
        bash_default_alias kE    "kubectl edit"
        bash_default_alias kS    "kubectl set"

        bash_default_alias kC    "kubectl create"
        bash_default_alias kA    "kubectl apply"
        bash_default_alias kP    "kubectl patch"
        bash_default_alias kdi   "kubectl diff"
        bash_default_alias kX    "kubectl expose"
        bash_default_alias kD    "kubectl delete"

        bash_default_alias kr    "kubectl run"
        bash_default_alias kx    "kubectl exec"
        bash_default_alias kpf   "kubectl port-forward"
        bash_default_alias kpx   "kubectl proxy"

        bash_default_alias kl    "kubectl logs"
        bash_default_alias ka    "kubectl attach"

        bash_default_alias kRO   "kubectl rollout"
        bash_default_alias kSC   "kubectl scale"
        bash_default_alias kAS   "kubectl autoscale"

        bash_default_alias kci   "kubectl cluster-info"
        bash_default_alias kt    "kubectl top"
        bash_default_alias kOn   "kubectl cordon"
        bash_default_alias kOff  "kubectl uncordon"
        bash_default_alias kDR   "kubectl drain"
        bash_default_alias kTT   "kubectl taint"

        bash_default_alias kK    "kubectl kustomize"
        bash_default_alias kc    "kubectl config"
        bash_default_alias ke    "kubectl explain"
        bash_default_alias khr   "kubectl api-resources"
        bash_default_alias kh    "kubectl help"
    fi
}
