#!/usr/bin/env bash
set -eu

Prefix=$1; shift

cat <<EOF
${Prefix}FontsFiles   := \$(${Prefix}Fonts:%=\$(FONTSDIR)/%)
${Prefix}FontsArchive ?= \$(shell basename \$(${Prefix}FontsURL))

\$(${Prefix}FontsFiles): \$(${Prefix}FontsArchive)
	@-./extract "$<" \$(FONTSDIR) "\$(@F)"

\$(${Prefix}FontsArchive):
	curl -C- -# -Lo \$@ -g \$(${Prefix}FontsURL)

InstalledFiles    += \$(${Prefix}FontsFiles)
IntermediateFiles += \$(${Prefix}FontsArchive)
IntermediateDirs  += \$(${Prefix}FontsArchive:%.zip=%)
EOF
