#!/usr/bin/env bash
# A script to run before my Mac goes to sleep
# See sleepwatcher (https://github.com/mxcl/homebrew/commits/master/Library/Formula/sleepwatcher.rb)
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2013-05-05
set -u
shopt -s extglob


# See-Also: http://atastypixel.com/blog/automatically-eject-all-disks-on-sleep-reconnect-on-wake/
ejectDisk() {
    local diskname=$1
    diskutil eject "$diskname" || (
        diskname=${diskname#/@(dev|Volumes)/}
        osascript -e 'tell application "Finder" to eject disk "'"$diskname"'"'
    )
    # TODO force unmountDisk if still there
    #diskutil unmountDisk force $diskname
}
ejectDisks() {
    while read diskname; do
        ejectDisk $diskname &
    done
}

# unmount all USB disks
system_profiler SPUSBDataType | grep 'BSD Name: disk\d+$' | sed 's/.*: //' | ejectDisks

# eject all remote time machine destinations first (sparsebundle)
tmutil destinationinfo | grep "Mount Point" | sed 's/.*: //' |
while read tmdest; do
    remotedisk=$(hdiutil info |
        sed -n '\#^image-path *: '"$tmdest"'#,/^==*$/{
            \#/Volumes/.*$#{ s#.*\(/Volumes/.*\)$#\1#p; q; }
        }')
    [ -n "$remotedisk" ] || continue
    ejectDisk "$remotedisk" &
done

# eject all remaining time machine destinations
tmutil destinationinfo | grep "Mount Point" | sed 's/.*: //' | ejectDisks

# To share Papers2 library over Dropbox, it has to be shut down
echo "Quitting Papers2"
osascript -e '
    # keep track of last active application
    set curAppPath to the path to the frontmost application
    set curAppName to the short name of (info for curAppPath)
    do shell script "ln -sfn " & (quoted form of POSIX path of curAppPath) & " ~/.wakeup.activate.app"
    do shell script "echo " & (quoted form of (name of the front window of application curAppName as text)) & " >~/.wakeup.activate.app.window"

    # shut down Papers2
    tell application "System Events"
        if exists process "Papers2" then
            do shell script "touch ~/.wakeup.Papers2"
            # keep track of in which Space/Desktop Papers2 were
            tell application "Papers2" to activate
            tell process "Papers2"
                set windowMenu to (first menu bar item whose title is "Window" or title is "윈도우") of menu bar 1
                click last menu item of menu 1 of windowMenu
            end tell
            tell application "Papers2" to quit
            #key code 12 using command down
        end if
    end tell
    '
# TODO wait until Dropbox finishes syncing Papers2's library


wait # for everything we wanted to do
#say "Sleeping..." # XXX any user interaction done here happens after wakeup
