#!/usr/bin/env bash
# A script to run before my Mac goes to sleep
# See sleepwatcher (https://github.com/mxcl/homebrew/commits/master/Library/Formula/sleepwatcher.rb)
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2013-05-05
set -u
shopt -s extglob

exec >~/.sleep.log 2>&1

PATH=~/Library/Scripts:"$PATH"

# Eject all external, backup volumes and disks
# XXX "Eject All External or Backup Disks.sh" &


# To share Papers2 library over Dropbox, it has to be shut down
echo "Quitting Papers2"
osascript -e '
    # keep track of last active application
    set curAppPath to the path to the frontmost application
    set curAppName to the short name of (info for curAppPath)
    do shell script "ln -sfn " & (quoted form of POSIX path of curAppPath) & " ~/.wakeup.activate.app"
    do shell script "echo " & (quoted form of (name of the front window of application curAppName as text)) & " >~/.wakeup.activate.app.window"

    # shut down Papers2
    tell application "System Events"
        if exists process "Papers2" then
            do shell script "touch ~/.wakeup.Papers2"
            # keep track of in which Space/Desktop Papers2 were
            tell application "Papers2" to activate
            tell process "Papers2"
                set windowMenu to (first menu bar item whose title is "Window" or title is "윈도우") of menu bar 1
                click last menu item of menu 1 of windowMenu
            end tell
            tell application "Papers2" to quit
            #key code 12 using command down
        end if
    end tell
    ' &
# TODO wait until Dropbox finishes syncing Papers2's library

# XXX Growl is less useful for OS X >= 10.9
#echo "Stopping Growl"
#osascript -e 'tell application "Growl" to quit' &

wait # for everything we wanted to do
#say "Sleeping..." # XXX any user interaction done here happens after wakeup
