#!/usr/bin/env bash
# A script to run before my Mac goes to sleep
# See sleepwatcher (https://github.com/mxcl/homebrew/commits/master/Library/Formula/sleepwatcher.rb)
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2013-05-05
set -u
shopt -s extglob

exec >~/.sleep.log 2>&1

PATH=~/Library/Scripts:"$PATH"

# Eject all external, backup volumes and disks
# XXX Disabling as it conflicts with PowerNap's TimeMachine backup
# "Eject All External or Backup Disks.sh" &

[ -e ~/.wakeup.apps ] || {
    cat >~/.wakeup.apps <<-EOF
	Papers2  # To share Papers2 library over Dropbox, it has to be shut down
	EOF
}

appsToRestart=($(sed 's/#.*$//' <~/.wakeup.apps))
echo "Quitting ${appsToRestart[*]}"
osascript -e '
    # keep track of last active application
    set curAppPath to the path to the frontmost application
    set curAppName to the short name of (info for curAppPath)
    do shell script "ln -sfn " & (quoted form of POSIX path of curAppPath) & " ~/.wakeup.activate.app"
    do shell script "echo " & (quoted form of (name of the front window of application curAppName as text)) & " >~/.wakeup.activate.app.window"

    '"$(for app in "${appsToRestart[@]}"; do echo '
    # shut down '"$app"'
    tell application "System Events"
        if exists process "'"$app"'" then
            do shell script "echo "& (visible of application process "'"$app"'") &">~/.wakeup.apps.'"$app"'"
            # keep track of in which Space/Desktop '"$app"' were
            tell application "'"$app"'" to activate
            try
                tell process "'"$app"'"
                    set windowMenu to (first menu bar item whose title is "Window" or title is "윈도우") of menu bar 1
                    click last menu item of menu 1 of windowMenu
                end tell
            end try
            tell application "'"$app"'" to quit
            #key code 12 using command down
        end if
    end tell
    '; done)" &

# TODO wait until Dropbox finishes syncing Papers2's library

#echo "Stopping Growl"
#osascript -e 'tell application "Growl" to quit' &

wait # for everything we wanted to do
#say "Sleeping..." # XXX any user interaction done here happens after wakeup
